language: ruby
cache:
  bundler: true
  directories:
    - vendor/bundle
env:
  matrix:
    - JEKYLL_VERSION="3.7"
    - JEKYLL_VERSION="4.0"
rvm:
  - 2.6
  - 2.7
matrix:
  fast_finish: true
branches:
  only:
    - master
